package com.questloop.app.util

import android.content.Context
import android.media.AudioAttributes
import android.media.AudioManager
import android.media.SoundPool
import com.questloop.app.R
import com.questloop.core.reward.CompletionChime
import com.questloop.core.reward.CompletionSound

/**
 * Plays the bundled quest-completion chimes (res/raw, generated by
 * scripts/generate_completion_sounds.py) at the loudness the core cue decided.
 *
 * A process-wide singleton so every surface (Today, Quests backlog, widget
 * quick-complete sheet, Rewards) shares one lazily-built [SoundPool]. Playback
 * is best-effort: any audio failure is swallowed — a chime must never break or
 * delay recording the completion itself. Silent/vibrate ringer modes are
 * respected (celebration is never worth an interruption the user muted).
 */
object CompletionSoundPlayer {

    private val rawByChime = mapOf(
        CompletionChime.PROGRESS to R.raw.chime_progress,
        CompletionChime.MINOR to R.raw.chime_minor,
        CompletionChime.MAJOR to R.raw.chime_major,
        CompletionChime.TRIUMPH to R.raw.chime_triumph,
        CompletionChime.LEVEL_UP to R.raw.chime_level_up,
    )

    private val lock = Any()
    private var pool: SoundPool? = null
    private var sampleByChime = emptyMap<CompletionChime, Int>()
    private val loadedSamples = mutableSetOf<Int>()

    /** The most recent request that arrived before its sample finished loading —
     *  played from the load callback so the very first completion still chimes. */
    private var pendingSample: Int? = null
    private var pendingVolume: Float = 0f

    fun play(context: Context, sound: CompletionSound) {
        runCatching {
            val app = context.applicationContext
            val audio = app.getSystemService(AudioManager::class.java) ?: return
            if (audio.ringerMode != AudioManager.RINGER_MODE_NORMAL) return
            synchronized(lock) {
                val p = pool ?: build(app)
                val sample = sampleByChime[sound.chime] ?: return
                val volume = sound.volume.coerceIn(0f, 1f)
                if (sample in loadedSamples) {
                    p.play(sample, volume, volume, 1, 0, 1f)
                } else {
                    pendingSample = sample
                    pendingVolume = volume
                }
            }
        }
    }

    /** Caller must hold [lock]. */
    private fun build(app: Context): SoundPool {
        val built = SoundPool.Builder()
            .setMaxStreams(2)
            .setAudioAttributes(
                AudioAttributes.Builder()
                    .setUsage(AudioAttributes.USAGE_GAME)
                    .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                    .build(),
            )
            .build()
        built.setOnLoadCompleteListener { p, sampleId, status ->
            if (status != 0) return@setOnLoadCompleteListener
            synchronized(lock) {
                loadedSamples += sampleId
                if (pendingSample == sampleId) {
                    runCatching { p.play(sampleId, pendingVolume, pendingVolume, 1, 0, 1f) }
                    pendingSample = null
                }
            }
        }
        sampleByChime = rawByChime.mapValues { (_, res) -> built.load(app, res, 1) }
        pool = built
        return built
    }
}
