package com.questloop.app.util

import android.app.NotificationManager
import android.content.Context
import android.media.AudioAttributes
import android.media.AudioManager
import android.media.SoundPool
import com.questloop.app.R
import com.questloop.core.reward.CompletionChime
import com.questloop.core.reward.CompletionSound

/**
 * Plays the bundled quest-completion chimes (res/raw, generated by
 * scripts/generate_completion_sounds.py) at the loudness the core cue decided.
 *
 * A process-wide singleton so every surface (Today, Quests backlog, widget
 * quick-complete sheet, Rewards) shares one lazily-built [SoundPool]. Playback
 * is best-effort: any audio failure is swallowed — a chime must never break or
 * delay recording the completion itself. Silent/vibrate ringer modes and Do Not
 * Disturb are respected (celebration is never worth an interruption the user
 * muted).
 */
object CompletionSoundPlayer {

    private val rawByChime = mapOf(
        CompletionChime.PROGRESS to R.raw.chime_progress,
        CompletionChime.MINOR to R.raw.chime_minor,
        CompletionChime.MAJOR to R.raw.chime_major,
        CompletionChime.TRIUMPH to R.raw.chime_triumph,
        CompletionChime.LEVEL_UP to R.raw.chime_level_up,
    )

    private val lock = Any()
    private var appContext: Context? = null
    private var pool: SoundPool? = null
    private var sampleByChime = emptyMap<CompletionChime, Int>()
    private val loadedSamples = mutableSetOf<Int>()

    /** Requests that arrived before their sample finished loading — played from
     *  the load callback so a first-launch burst of completions still chimes. */
    private val pendingPlays = mutableListOf<Pair<Int, Float>>()

    fun play(context: Context, sound: CompletionSound) {
        runCatching {
            val app = context.applicationContext
            if (!audible(app)) return
            synchronized(lock) {
                val p = pool ?: build(app)
                val sample = sampleByChime[sound.chime] ?: return
                val volume = sound.volume.coerceIn(0f, 1f)
                if (sample in loadedSamples) {
                    p.play(sample, volume, volume, 1, 0, 1f)
                } else {
                    pendingPlays += sample to volume
                }
            }
        }
    }

    /** True when a celebration chime is welcome: ringer on and no DND filter. */
    private fun audible(app: Context): Boolean {
        val audio = app.getSystemService(AudioManager::class.java) ?: return false
        if (audio.ringerMode != AudioManager.RINGER_MODE_NORMAL) return false
        val filter = app.getSystemService(NotificationManager::class.java)?.currentInterruptionFilter
        // UNKNOWN means we can't tell — allow rather than silently drop forever.
        return filter == null ||
            filter == NotificationManager.INTERRUPTION_FILTER_ALL ||
            filter == NotificationManager.INTERRUPTION_FILTER_UNKNOWN
    }

    /** Caller must hold [lock]. */
    private fun build(app: Context): SoundPool {
        val built = SoundPool.Builder()
            .setMaxStreams(2)
            .setAudioAttributes(
                AudioAttributes.Builder()
                    .setUsage(AudioAttributes.USAGE_GAME)
                    .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                    .build(),
            )
            .build()
        built.setOnLoadCompleteListener { p, sampleId, status ->
            if (status != 0) {
                // A sample that failed to load will never play: drop its queued
                // requests too, or they'd accumulate for the life of the process.
                synchronized(lock) { pendingPlays.removeAll { it.first == sampleId } }
                return@setOnLoadCompleteListener
            }
            synchronized(lock) {
                loadedSamples += sampleId
                val due = pendingPlays.filter { it.first == sampleId }
                pendingPlays.removeAll { it.first == sampleId }
                // Re-check audibility: the user may have muted during the load window.
                val context = appContext
                if (context != null && runCatching { audible(context) }.getOrDefault(false)) {
                    due.forEach { (sample, volume) ->
                        runCatching { p.play(sample, volume, volume, 1, 0, 1f) }
                    }
                }
            }
        }
        appContext = app
        sampleByChime = rawByChime.mapValues { (_, res) -> built.load(app, res, 1) }
        pool = built
        return built
    }

    /** Test hook: the built pool (null when a mute gate stopped [play] early). */
    internal fun poolForTesting(): SoundPool? = synchronized(lock) { pool }

    /** Test hook: releases the cached pool so each test starts cold — the
     *  singleton otherwise leaks one test's Application into the next. */
    internal fun resetForTesting(): Unit = synchronized(lock) {
        runCatching { pool?.release() }
        pool = null
        appContext = null
        sampleByChime = emptyMap()
        loadedSamples.clear()
        pendingPlays.clear()
    }
}
